"""
Django settings for auto project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3ighcobk(i#)1p%m_5mj64+f(%*f1s$x+@03!p%$)7_27@lom)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['localhost','127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fb',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

EXCELFILES_URL = '/excelfiles/'  # This will match the path in the JS
EXCELFILES_ROOT = os.path.join(BASE_DIR, 'excelfiles')  # Path where your files are stored

ROOT_URLCONF = 'auto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auto.wsgi.application'

ASGI_APPLICATION = 'auto.asgi.application'  # Replace 'your_project_name' with your project folder name

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# e5c486295d17c25b9c92
# app_id = "1898740"
# key = "e5c486295d17c25b9c92"
# secret = "c6ac9514bb8b9d4a4e57"
# cluster = "ap2"
PUSHER_APP_ID = '1898740'
PUSHER_KEY = 'e5c486295d17c25b9c92'
PUSHER_SECRET = 'c6ac9514bb8b9d4a4e57'
PUSHER_CLUSTER = 'ap2'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db1.sqlite',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',  # MySQL backend
#         'NAME': 'egeeksglobal',          # Your database name
#         'USER': 'zaheer1',          # Your MySQL user
#         'PASSWORD': '12345678',  # Your MySQL password
#         'HOST': 'db4free.net',                   # Database host (use 'localhost' or an IP)
#         'PORT': '3306',                        # Default MySQL port
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'
USE_TZ = True  # Ensure this is True to enable time zone support

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# Base directory of your project
BASE_DIR = Path(__file__).resolve().parent.parent

# settings.py
STATIC_URL = '/static/'

# Add the path to the static directory if it is outside the app's directory
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Ensure this points to an existing directory
]

STATIC_ROOT = BASE_DIR / 'staticfiles'
# Directory where collectstatic will gather all static files for production


# Optional: Directories Django should search for additional static files
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),  # Project-level static directory (if any)
# ]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session settings
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days in seconds
SESSION_SAVE_EVERY_REQUEST = True  # Save the session on every request
SESSION_COOKIE_SECURE = False  # Allow cookies on HTTP
SESSION_ENGINE = 'django.contrib.sessions.backends.file'  # Use file-based sessions 
SESSION_FILE_PATH = os.path.join(BASE_DIR, 'sessions')  # Custom path for session files

# Ensure session directory exists
os.makedirs(SESSION_FILE_PATH, exist_ok=True)

# Cookie settings
CSRF_COOKIE_SECURE = False  # Allow CSRF cookies on HTTP


